---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: squash-assistant-huddle-bot
  namespace: squash-assistant
spec:
  encryptedData:
    HUDDLE_BOT_MCP_API_KEY: AgAHMdhXxfoJyQy4ODqzyVIW6IU3USIoR61Y547bPMNTg1CGifxZm7Ngb4UmORa5FoGrK+gYTMRrTDJ90OUYkSDP0gc+++iFNughVf+LOV4GXW22b54yvAMAWEmTf24N5BClzsr5mi5h4rIk9c3zvGHAOdcLkNMojPHoGH82svtIW4x0hS8czGgMFyJ3YiT8RJZpQ8KwaFDgCBUwcjPuwrKJLFbj23d1lMzIvAGOqu9sa2dcILEO54Qedm2u8+OqWg5lUlxIpRA71TSuIlPOLhtfAHxmw2qTJnBFTN6ETJVx5AiqwoAtWVuaipB+hqC9kPU7CkHE1euPu1g9O5rXy8vPUlnajphUrHVMaoApeSZfPw7G6a7d218jc+UjJhHpfs9TduW8TOfimrGzlPdu620GnKTSuY+KGyxoI2pQAGc2utpa2qvF2kP9jadnSS/ftgqPTq7xlS7ZX5WlaZZLmnbA5VSLnCKvhWq77IHKPtuJzN4lw3zkomFjuuLPsEi364TrIfJkfc3+JU1pSpLzSI3yQqWL8jNDw8EppRKKb6ISutdiVeaC/vL38UYQBfAl3NS/fdh0rxCUN95NLLG7Yv/oNtk8b0iXJZYk1IhgN/GwCJdhkaewxu5zVegNzFpN7Ic8o0u4vUhm7Poqc7yOwH4ZhewY5rhNzcwGIazK6bgC1pLfl5tnLGoHm5lb0mInEMgtypzfXX5TsO2ztVY1J+Dk5nLaHVmMffcE/FD0mdlfliLodIpsLXb6hhuMA8c00N5wJktYr8c6QMEdVm0TtPRK1HfeqAv8dXs=
  template:
    metadata:
      name: squash-assistant-huddle-bot
      namespace: squash-assistant
