---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: squash-assistant-huddle-bot
  namespace: squash-assistant
spec:
  encryptedData:
    HUDDLE_BOT_MCP_API_KEY: AgAZS9qFnF8LUqWopGfnckNxo464k9y+q9QEVCsOoRt46EOaaLdagMzV92ZZTDSdlWhYTM6q93RSd08PNOJgP4LZvyVXXl0jKRfbZgNUUbZdME9TWTK25t6amcydf1w3qrv/N0pMDlKSq0TESVNmLk24QJ0+enlabEyf/+P+d58z0BuiY5aGV5Mrqc3+GK4RnTmM0k4tkYG0M1CfBAh8YT1WvQ17+JjMj8Yg5Xl//Ww3cKQbbWCeFrITEjLtqOrNH1sYKBaFsVN2EFFoLackwcOZywEe9LIe4ec7U9XCCO/T/+mBERiSovKl4GOmuUHQtkjFOW7JzQzlMlkMkgxJM3JUEDlp7Djfk9zeAbe4ItxG6VKHAasEOfm4UzlmNTZude6yERFdevGLbvy+Gb/aQEUAjW+uTd8Fa+DYb+4hA8EbvTZzfKPz7KEUI71hvz0jqazCXcaH6vTmHlLfeDZmG4KNF1zV23FsYAJdCAPiqUmC3KqiT7QUCVj+jQ6Lxd0scaFGJ28TE+9qhisvTvL/3qOiys1IKMOda8HhJn2zI32rLPo/evFlJ7m/I9K+F0Sm+eY3SD1tFyaVhlKb7cP0811XEFMEQ0PZ73494Vd7VV9XjMXhYCgCZ78tQ/JB9Ucf4JS5dioLpuaouiD1iZNBuihFBtWbydnztdFA1iVlbklvsbM9RmUzC09B2iSE9mp7B7rTtMC6/Yzoy//+fI6rGAHypSEPYRSGCrjGAHYzEPTAaE7IKTphlLTeB23kNyRj7ENt7pqjwWv23iTcO8WvEHuV8tl61pvhKAE=
  template:
    metadata:
      name: squash-assistant-huddle-bot
      namespace: squash-assistant
