---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: squash-assistant-postgres-password
  namespace: squash-assistant
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgB2iCrMBuCL6Dou18TmGwTCSLQfibG1XP7qnrkvKCoCjuUEljrvlQzmMpLj06cG2yESupPomXLV5PINpit2UR+9581ShxbSur1uW8ycRLC+2wcJPmxmKCntag9rlvFw65XSjCEdN6YubQ1BX01wfRJ3PJ7ZgYpePoNnV65eDIwjSqwZGg1kp5Oj5hhvqDVYG9CQ/dop8ojk2f95lFP6z2iMwc3+cjBiqECz4L9aso7wdjT3h5C+zHBVOstpirbCfxvXNJbx4MOSG+pVw8BXH0bhnsiH4+/yRdxoyQSfbXeaQeUtrv5DjRlPMpQE0YPZ1jM3V4RPPJjPcSakFuBDrRAtlffF5geFNIezvuDxy/cM5HIiCW6FTrkp02Uzr6/uORQqLq+dQ0d5tNJ2VaBgUGjA+Q7h5livdBexTXkEM+F+ViDzRKUJN0lHTg/nLLGrNHR+053sNYHzFjn9Huj40DLLjP2nyUDDTkEV1/arOjILmpyOe0EJMn0fE3DpoqGMZ1AvIrghgsrm/X1OVn08+GJvqViJ+UnJz/QgACH0M9Fz8GlrWBQuIioMqpurmSgwLOwUIkzzs7l1ymsaJ09on+EBj/tSf7i6+MafVo+WHcbeuRb4Y8bnCJS0Eh4fb/tLJe/mFDUC/FttuI2KojUFLyYVsLVI3WTsAvWKozfFupYzAzulnGGRNBQp4KmfoDEG17qYWzKo/gZzKwT1hwNtC4nJ088RkRqn9YUzCbScuU9N
  template:
    metadata:
      name: squash-assistant-postgres-password
      namespace: squash-assistant
